---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is success
  retries: 5
  delay: 2
  with_items: "{{ process_exporter_dependencies }}"

- name: Create the process_exporter group
  group:
    name: "{{ process_exporter_system_group }}"
    state: present
    system: true
  when:
    - process_exporter_system_group != "root"

- name: Create the process_exporter user
  user:
    name: "{{ process_exporter_system_user }}"
    groups: "{{ process_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when:
    - process_exporter_system_user != "root"

- name: create prometheus data directory
  file:
    path: "{{ process_exporter_config_dir }}"
    state: directory
    owner: "{{ process_exporter_system_user }}"
    group: "{{ process_exporter_system_group }}"
    mode: 0755

- name: Download process_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/ncabatoff/process-exporter/releases/download/v{{ process_exporter_version }}/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ process_exporter_checksum }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack process_exporter binary
  become: false
  unarchive:
    src: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
  delegate_to: localhost
  check_mode: false

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Propagate process_exporter binaries
  copy:
    src: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
    dest: "/usr/local/bin/process_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart process_exporter
  when: not ansible_check_mode
